### ISSUE TITLE
Prepare for important involvement of @elipousson

### ISSUE THREAD

**Issue by florisvdh** [r-spatial/rgeopackage#7]
@edzer it appears that @elipousson is going to boost this package to a level much higher than currently the case :rocket:. See #4 and his fork https://github.com/elipousson/rgeopackage.

For that reason, it seems best to add him to r-spatial and/or this repo, at least what is needed so that he can do maintenance/authoring work more easily.

@edzer (or others) is that OK with you and could you handle that? At least I didn't find how I can give him write access to the **rgeopackage** repo, so that he can make e.g. branches and pull requests inside the repo.

@elipousson please respond if you see things different (but the signs make me add this issue :slightly_smiling_face:).

**Comment by edzer** [comment]
OK, @elipousson now has write access. Welcome to r-spatial Eli!

**Comment by florisvdh** [comment]
Great, thanks Edzer.
